### ISSUE TITLE
(#137) Set up Google Analytics

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#133]
### Done criteria
- [x] Generated an api key for analytics module
- [x] Add API key to drupal
---
### ALNAP to check
- [ ] They have access to site analytics on their google account

**Comment by Maria-alnap** [comment]
@nadia847 @dave-manta @ican-icant @russ-manta @matty-manta (not sure who to tag for this so I'm telling you all!)

As mentioned in our last catch up, we met with the ODI person leading on all things digital and she had some suggestions on how to set up Google Analytics on our new site that we'd like to take on board. She also suggested that we set up the dashboard as part of our training, as that's a good way of learning how it all works. She was wondering whether you'd be using the traditional dashboard or Google Dat Studio? 
Now, to the point, and apologies in advance if some are obvious but we're kind of new to this (we've dealt with a dinosaur thus far, just remember that!):

Set up the tag manager option instead of just basic Google Analytics code
Set up at least 3 views: Unfiltered, main (incl staff filter, others tbc) and test
Keep portals as different properties within our account
Set up the following basic permanent goals: 
- PDF downloads
- login tracker
- newsletter sign up tracker
- new signups, scroll tracking
- social media shares
- exit to other sites

Set up more sophisticated goals to:
- track social media and AV (e.g. user behaviour with youtube clips, prezis, etc.)
- track reading time on content pages (topics, blogs)
- check which anchors get clicked on the most (subtopics on topics pages)
- check logged in ppl reading of specific content types (e.g. Member updates)
- check user journeys to the HELP Library: search from ALNAP homepage v search on HELP Library itself.

I think this is it for now. Hope it makes sense!

**Comment by dave-manta** [comment]
@Maria-alnap Thanks for the info.  We'll need Russ to pick this up when he's back from hols next week.
