### ISSUE TITLE
Clarify blog submission process

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#157]
- [x] Will they ever have non members (ie people without a login)/subscribers submitting blogs?
- [x] What is the actual process?

In summary (from below)
-----------------------------------
Any interested party submits their blog post to ALNAP for review.  ALNAP then create the blog post and link it to the person's account. If they don't have an account then ALNAP first create them one.

**Comment by russ-manta** [comment]
@Maria-alnap could you answer these questions for us please?

**Comment by Maria-alnap** [comment]
@russ-manta @nadia847 
Q1: Yes and no. People with no accounts can pitch blog posts to us but when their piece is published, the current site needs to connect the author to a subscriber ID. This means that we need the author to create an account with us if he doesn't have one already. (In practice, we end up creating them ourselves in the backend, otherwise it would take even longer to publish posts).

Q2: The process is that any interested parties in writing a post email a pitch to us, we liaise with them on the drafting/editing process, we then upload the signed off post connected to an ID as mentioned in previous Q.

Happy to change the workflow to something that makes more sense to you, if there is any :)
