### ISSUE TITLE
(#247) Migrating blog comments programatically

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/alnap#206]
Migrating blog comments was initially out of scope but after Russ provided a quote of  £560 plus VAT for doing it  programatically, Maria has agreed and it's come into scope. 

---
### Dependencies
- [x] Build and theme comments #194 
- [x] ALNAP need to have migrated in the content first
---
### Done criteria for scoping
- [x] @russ-manta  to provide an estimate for how long it would take to do a manual migration vs a programatic migration.
- [x] Made decision on manual or **PROGRAMATIC** migration

### Done criteria for migration 
- [x] Export comments from ALNAP site - see attached file blog_comments_for_import.zip
- [x] Match original comment pages to node ids in Drupal
- [x] Import into DISCUS with all relevant fields
- [x] Ensure comments display on correct pages and in order
---
### ALNAP to check
- [ ] Comments displaying on correct pages with correct authors and order

[blog_comments_for_import.zip](https://github.com/MantaRayMedia/alnap/files/1396457/blog_comments_for_import.zip)

**Comment by angievanhegan** [comment]
@Maria-alnap So that we don't forget this and you don't have to ask us again (!) I've created a separate issue for this. Hope that's ok.

**Comment by Maria-alnap** [comment]
Thanks @angievanhegan . Happy to speak to @russ-manta next week

**Comment by angievanhegan** [comment]
@Maria-alnap Great. I've put this on the agenda for the meeting on Monday.

**Comment by russ-manta** [comment]
@Maria-alnap I've discovered that there are 138 blog comments. I estimate this would take you approximately 2 days to migrate manually.  For us to do the import to Drupal or Disqus I estimate would probably take approximately 1 day at £560 +VAT

**Comment by Maria-alnap** [comment]
@russ-manta @angievanhegan please go ahead with migrating this yourselves. I will add it to my "in scope" spreadsheet. This would need to updated in the invoice you sent, @dave-manta @ican-icant

**Comment by angievanhegan** [comment]
@Maria-alnap I received this reply from Disqus. I hope it helps. 

Thanks for reaching out. To clarify, Disqus is not applying any tax to subscription fees. Invoice receipts are emailed to publishers providing invoice #s and other Disqus company information for those who wish to use them for tax purposes, but no taxes are applied to the subscriptions.

**Comment by Maria-alnap** [comment]
@angievanhegan thanks! Very helpful :)

**Comment by angievanhegan** [comment]
@russ-manta Please can you add some done criteria and estimate this? I think it's going to hvae to go in the next sprint though.

**Comment by angievanhegan** [comment]
@russ-manta for launch, ALNAP won't have migrated over all the blog items that they want (there are some old and popular ones which they'll bring across later). @Maria-alnap asked if it's possible to migrate some of the comments now (for the blog items they've migrated) and the other ones later (for the ones they'll migrate later)? Thanks

**Comment by russ-manta** [comment]
@Maria-alnap @angievanhegan yes I think this is ok. What we could do is create some empty blog posts for the ones which you plan to bring over later (and leave these unpublished) and then bring over all of the comments at once anyway ready for you to complete the content when you have time.  Could you provide a list of the blogs you will/won't be bringing over for launch?

**Comment by Maria-alnap** [comment]
@russ-manta We've looked at our analytics and we have decided that we will only migrate blogs from the beginning of 2014 until now. I will finish these by Thursday, so you can migrate comments whenever you want after that :)

**Comment by russ-manta** [comment]
@meldera can you take a look at this? Note comments need to be migrated into DISCUS

**Comment by russ-manta** [comment]
@cutlern we have some blog comments to import into Disqus and I think there are also some dummy ones to remove. Let me know when you're ready to talk about this

**Comment by cutlern** [comment]
Couple of accounts need verification before their comments (and the ones after) can be added

juanluis.dg@gmail.com / ai.sumihira@gmail.com

**Comment by russ-manta** [comment]
[blog_comment_issues.zip](https://github.com/MantaRayMedia/alnap/files/1401416/blog_comment_issues.zip)

Blog comment issues

**Comment by russ-manta** [comment]
@Maria-alnap we've added most of the comments now. Unfortunately it wouldn't let us add the original dates but we've added them in date order.  There are a few outstanding in the blogs_comments_issues.zip file above which we can;t add as these people don't have disqus accounts.  Do you want us to add these under another name, add and get them to verify their emails address (ie sned them an email to create an account) or just leave them?

**Comment by Maria-alnap** [comment]
@russ-manta @cutlern please do!

**Comment by cutlern** [comment]
@Maria-alnap Sorry, do you mean you want us to add them or leave them?

**Comment by Maria-alnap** [comment]
@cutlern please add them, I meant!

**Comment by Maria-alnap** [comment]
I found a few missing in a quick survey, I've detailed them below (didn't go through all the blogs). Are these due to missing email addresses/accounts, if so do we have a work around? (Tim)

['New year new you'](https://www.alnap.org/blogs/new-year-new-you-what-the-whs-can-learn-from-failed-new-year%E2%80%99s-resolutions) had three comments on it previously (Ephraim Amos, Carlisle Levine, John Borton)

['Is palliative care in humanitarian crises a luxury?'](https://www.alnap.org/blogs/is-palliative-care-in-humanitarian-crises-a-luxury) had four comments on it (Juan-luis Dominguez, Roots Bondowe Muhindo Virihi, Elysee Arequipa Nouvet x2)

['A job well done is the best possible humanitarian motivation' ](https://www.alnap.org/blogs/a-job-well-done-is-the-best-possible-humanitarian-motivation) had two (John Mitchell, Loy Rego)

[A hunter gatherers response to the Indian Ocean Tsunami; an aspiration for the international humanitarian system?](https://www.alnap.org/blogs/a-hunter-gatherers-response-to-the-indian-ocean-tsunami-an-aspiration-for-the-international) had two (Ai Sumihira, Leitmann Josef)

**Comment by cutlern** [comment]
Hi Maria! A few of these are identified in the blog comment issues zip above:

-'New year new you': John Borton's comment needed ALNAP moderating, Carlisle Levine's comment need's ALNAP verification. 
-'Is palliative care in humanitarian crises a luxury?' these comments will be added once Juan-luis Dominguez's account is sorted
-'A hunter gatherers response to the Indian Ocean Tsunami; an aspiration for the international humanitarian system?' same issue as above

I'm not sure why John Mitchell/Loy Rego's comments are missing, because i've marked them as added, i'll try again and see if there's an issue. Also, I can't actually see Ephraim Amos's name/comment on the original csv you linked us, is his a newer comment?

**Comment by Maria-alnap** [comment]
Hi @cutlern! Apologies - it's Tim pretending to be Maria (she's on leave this week). I'm not totally up to speed on this, so I'm sorry if I'm going over old ground/being confusing:

- New year new you: where would these be moderated/verified? I've just logged into our Disqus account but I can't see any outstanding comments...
- Ephraim Amos: sorry, that one was my mistake, ignore me! I was going by the old ALNAP site and just realised we hadn't actually verified that one.

Otherwise, it's all looking good!
