### ISSUE TITLE
(#137) Review / adjust content type aliases & breadcrumbs

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#221]
### Done criteria
- [x] Set up menu position rules
- [x] Train client on setting up menu position rules
- [x] Check content types have correct breadcrumbs
- [x] Check content types have correct aliases
- [ ] Explain to ALNAP what an alias is in this context
---
### ALNAP review criteria 
- [x] Check content types have correct breadcrumbs
- [x] Check content types have correct aliases

**Comment by angievanhegan** [comment]
@russ-manta Does this relate to any of our (future) sprint goals? Thanks

**Comment by Maria-alnap** [comment]
@russ-manta breadcrumbs are fine, but I'm afraid I don't know what an alias is! Could you let me know and I'll check.

**Comment by angievanhegan** [comment]
@matty-manta do you have a second to explain this to @Maria-alnap please? Thanks

**Comment by matty-manta** [comment]
Hey @Maria-alnap (Alex)

The alias is just the url that is given to any created piece of content, eg when you add a blog, is the path something like: http://alnap-dev.mrmdev.co.uk/blogs/a-blog-title (with "blog" in the url). 

And making sure that structure is repeated for other relevant content types, events within events, etc.

Hope that make sense, let me know otherwise.
Matty

**Comment by Maria-alnap** [comment]
All good and clear. Moving it to done now :)
