### ISSUE TITLE
Resources iframe

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/alnap#288]
### Done criteria
- [x] Display prezi on resources - iframe is currently blocked eg.http://alnap-dev.mrmdev.co.uk/help-library/the-state-of-the-humanitarian-system-2015-launch-prezi
- [x] Ensure souncloud also works via soundcloud nugget

---
### ALNAP to check
- [x] Can display prezi on resources
- [ ] Can embed soundcloud clips

**Comment by meldera** [comment]
Added an IFrame field and a Body filter to the resources admin view. Frames will have to be moved manually.

**Comment by russ-manta** [comment]
@meldera can you take a look at the soundcloud issue: http://alnap-dev.mrmdev.co.uk/events/3rd-asop-conference

**Comment by meldera** [comment]
Using the wrong nugget for soundcloud.

**Comment by Maria-alnap** [comment]
@russ-manta thanks for this. I haven't ticked the last box as we still prefer the way the soundcloud widget looks. Alex and @nadia847 have been talking about this in slack and she said that you could tweak it. I'll paste convo below: 

commented on @alex’s file website soundcloud widget error.PNG: The problem with the soundcloud nugget is that it shows up as a big square, rather than the long thin rectangle that you can import if you use an iframe widget - can the soundcloud nugget be changed to look like the widget? We're happy to use the iframe widget, but I can see you mention these might not be functional on the website?

nadia [12:12 PM] 
commented on @alex’s file website soundcloud widget error.PNG: we should be able to style the nugget…

**Comment by russ-manta** [comment]
@nadia847 can you look at the soundcloud issue please?

**Comment by nadia847** [comment]
@russ-manta fixed.

**Comment by Maria-alnap** [comment]
@russ-manta @nadia847 thanks for this. Any chance you could tweak it so that it shows up a bit thinner?

**Comment by nadia847** [comment]
@Maria-alnap is it better now?

**Comment by Maria-alnap** [comment]
@nadia847 looking better. If we wanted it just to be a plain background, is that something you can tweak or we'd need to strip things back in our soundcloud account?

**Comment by nadia847** [comment]
@Maria-alnap I'm afraid you'll have to make that change in soundcloud.
