### ISSUE TITLE
(#215) Build RSS feeds

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#69]
Links to #142 - weekly email mailouts for jobs and events

---
### Done criteria
- [x] ALNAP general feed (all website updates) - use main content nuggets and truncate to 250/300 characters - may need to strip come tags
- [x] Events feed - use main content nuggets and truncate to 250/300 characters - may need to strip come tags
- [x] Jobs feed - should work with exisiting RSS displays

---
### ALNAP to check
Review feed for the following:
- [x] ALNAP general feed (all website updates) http://alnap-dev.mrmdev.co.uk/rss.xml

**Comment by nadia847** [comment]
Do we need all of the above views?

**Comment by dave-manta** [comment]
@nadia847 have asked the client on the slack channel.  Pasting the link for reference. http://www.alnap.org/feeds

**Comment by angievanhegan** [comment]
@russ-manta Is there any urgency to know the answer to this? Just wondering if it would be better to know earlier in the build process, or we can park it for later? Thanks

**Comment by dave-manta** [comment]
@angievanhegan I don't believe there is any urgency for this.

**Comment by russ-manta** [comment]
@angievanhegan let's park it for now

**Comment by angievanhegan** [comment]
On this page http://www.alnap.org/feeds you have a number of RSS feeds. Are they all needed? Do you have a feel for how much they are used? Could we just get away with a single feed? (edited)

mgili [2 days ago] 
dave: I need to ask Phil about this, as I assume these feeds are the ones that populate our automatised jobs and vacancies mailouts...

mgili [2 days ago] 
Which is what I was thinking to go for when using news to populate our newsletter too (I know I'm getting into something else here so I'll stop now :))

dave 
[2 days ago] 
If we're doing the weekly mailouts (which I believe was costed), then we may use RSS feeds, although we do have other ways of implementing this.  I think it's better to decide if they are useful for users rather than how they are used by the site or ALNAP!  Do you think they are used?

dave
[1 day ago] 
My recommendation is that we start with single feed and any others in the future if needed @mgili


mgili [23 hours ago] 
Phil has confirmed that the feeds don’t power anything and are just there as legacy functionality. The jobs and vacancies emails are generated directly from the database and not via the feeds.

**Comment by angievanhegan** [comment]
@Maria-alnap Can you confirm that this list of feeds is correct? Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan I have only ticked a couple of the above, which are the ones that we would like to keep.

**Comment by nadia847** [comment]
@angievanhegan @Maria-alnap we'll still need the Events and Jobs ones for the automated mailouts so I'm keeping those in the list :o)

**Comment by Maria-alnap** [comment]
@nadia847, thanks for confirming that. I wasn't sure whether you'd be using feeds for those in the end :)

**Comment by dave-manta** [comment]
![image](https://user-images.githubusercontent.com/29146225/29659670-e641c774-88b6-11e7-811b-099589269f1f.png)

**Comment by dave-manta** [comment]
![image](https://user-images.githubusercontent.com/29146225/29659706-ff0fddea-88b6-11e7-9e0c-458e1b6c947f.png)

**Comment by cutlern** [comment]
http://alnap-dev.mrmdev.co.uk/events/rss.xml
http://alnap-dev.mrmdev.co.uk/rss.xml
http://alnap-dev.mrmdev.co.uk/jobs/rss.xml

**Comment by russ-manta** [comment]
@cutlern I've had a look and chatted with Arseni and Nadia and we think we should change the views to use fields. Can you do this please as it should give us greater control over the html output in the feeds.

Thanks
