### ISSUE TITLE
(#213) Build Resource management view

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#71]
some kind of big sortable, filterable table for web editors

### Done criteria
- [x] Create a VBO view of resources with filters as on help library to enable ALNAP to edit/delete resources in bulk
- [x] Bulk sticky (for promoted alnap resources)
---
### Designs
- [ ] N/a
---
### ALNAP to check
see http://alnap-dev.mrmdev.co.uk/admin/content/resources
- [x] Can filter and select resources to edit as needed
- [x] Can bulk update tags (see #94) and add sticky

**Comment by angievanhegan** [comment]
@russ-manta I think this is a candidate for bringing into the sprint if we have space. Broadly under the goal, but could be a reasonable size?

**Comment by russ-manta** [comment]
@angievanhegan yes could be a good one won't take too long

**Comment by nadia847** [comment]
@dave-manta could you please brief arseni on this?

**Comment by dave-manta** [comment]
@nadia847 probably needs a discussion with you or Russ beforehand and input from ALNAP.   When does this work need to start?

**Comment by dave-manta** [comment]
![image](https://user-images.githubusercontent.com/29146225/29659090-0b4fc90a-88b5-11e7-8b3a-b736c5c4a5c0.png)

**Comment by meldera** [comment]
http://alnap-dev.mrmdev.co.uk/admin/content/resources

**Comment by nadia847** [comment]
@meldera I think we should use chosen on the filters...

**Comment by Maria-alnap** [comment]
Hey gang, a few issues with this one: 

Selecting resources
1. When you apply a criteria to the search, when the results show, the other selection boxes at the top malfunction (same as bulk upload)
2. You can't deselect a criteria once you've clicked it - you have to change it to another criteria in the same box (which we might not always want to do) (same as bulk upload)

Editing resources
1. Hide from HELP Library options are currently 'none', 'HELP' and 'ECB' - it needs to show 'Yes' or 'No'
2. The resrouce catagory currently says 'current' 'past' 'operational' and 'analysis' - is this is same as the crisis catagory? If yes, we've currently got: 'Research, policy and analysis'
'Learning and evaluation of similar crises' and 'Current learning and evaluation'
3. Under publisher it asks if it's an ALNAP resource, then again under contributor, it asks if it's an ALNAP or Member resource. 
4. Under 'Link' there is no box

(Alex)

**Comment by russ-manta** [comment]
@Maria-alnap Alex,
Selecting resources
1. Do you mean some of the boxes are emtpy with no options? If so, this is because for the resources you have filtered they don't  have any content for those fields. This will happen less once all the resources have been entered.
2. You should be able to deselect a criteria by holding down ctrl and clicking the item.

Editing resources
1. Hide from HEP library now changed to Yes/No
2. Crisis category options have now moved to tags under 'Syria crisis' as asked for by Maria - imported items are using the terms under resource category which we are importing from the database eg. Current = 'Current learning and evaluation' -  these items will need to be retagged and then resource category will be removed
3. There is a reson for this - I'll confirm what it is tomorrow
4. Link gives you the option to add a title and url for the link - which are just beneath link - appreciate this might not seem obvious to start with

Russ

**Comment by Maria-alnap** [comment]
Hi @russ-manta 

Great! Happy with all of those! Ticked off now.
